version: '3'

networks:
  althcms_api_eform_net:

services:
  nginx:
    image: nginx:1.17-alpine
    container_name: althcms_api_eform_nginx
    restart: unless-stopped
    depends_on:
      - app
      - sqlserver
    ports:
      - 8002:80
    volumes:
      - ./src:/var/www/html
      - ./nginx/:/etc/nginx/conf.d/
    networks:
      - althcms_api_eform_net

  sqlserver:
    image: microsoft/mssql-server-linux:2017-latest
    container_name: althcms_api_eform_mssql
    ports:
      - "14332:1433"
    volumes: 
      - ./mssql/data:/var/opt/mssql
    environment:
      SA_PASSWORD: "AdminSqlServer123"
      ACCEPT_EULA: "Y"
    networks: 
      - althcms_api_eform_net

  app:
    build: 
      args:
        user: febrianrz
        uid: 1000
      context: .
      dockerfile: Dockerfile
    container_name: althcms_api_eform_php
    volumes: 
      - ./src:/var/www/html
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    ports: 
      - "9002:9000"
    networks: 
      - althcms_api_eform_net
    links:
      - sqlserver